apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: microservice-app-example
  labels:
    app: auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: danieljaraba/auth-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: ZIPKIN_URL
              value: http://zipkin:9411/api/v2/spans
