apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: microservice-app-example
  labels:
    app: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: danieljaraba/users-api:latest
          ports:
            - containerPort: 8083
